services:
  apache-1c:
    build: .
    container_name: apache-1c
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      # Конфиг сайта Apache
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      # Глобальный ServerName
      - ./config/servername.conf:/etc/apache2/conf-enabled/servername.conf:ro
      # Публикация 1С (VRD и статические файлы)
      - ./www/base:/var/www/base:ro
      # Библиотеки/модуль 1С с хоста (wsap24.so и зависимости)
      - ${ONEC_DIR}:/opt/1cv8/platform:ro
    deploy:
      resources:
        limits:
          cpus: "2.0"     # максимум 2 vCPU
          memory: 1G      # максимум 1 ГБ ОЗУ
        reservations:
          cpus: "0.50"    # мягкий резерв (не обязательен)
          memory: 512M

